

package userinterface.CustomerRole;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  monal
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;
 
    
    /** Creates new form AdminWorkAreaJPanel */
    public CustomerAreaJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system) {
        initComponents();
        this.account=account;
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        //this.restaurant=restaurant;
        //this.account=account;
      
        valueLabel.setText(account.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateInfo = new javax.swing.JButton();
        viewOrders = new javax.swing.JButton();
        placeOrder = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area - Customer Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        updateInfo.setBackground(new java.awt.Color(8, 34, 137));
        updateInfo.setForeground(new java.awt.Color(255, 255, 255));
        updateInfo.setText("Manage Personal Information");
        updateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoActionPerformed(evt);
            }
        });
        add(updateInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 310, -1));

        viewOrders.setBackground(new java.awt.Color(8, 34, 137));
        viewOrders.setForeground(new java.awt.Color(255, 255, 255));
        viewOrders.setText("View Past Orders");
        viewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersActionPerformed(evt);
            }
        });
        add(viewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 310, -1));

        placeOrder.setBackground(new java.awt.Color(8, 34, 137));
        placeOrder.setForeground(new java.awt.Color(255, 255, 255));
        placeOrder.setText("Place an Order");
        placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderActionPerformed(evt);
            }
        });
        add(placeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 310, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Customer:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoActionPerformed
        // TODO add your handling code here:     
        PersonalInfo personalInfo=new PersonalInfo(userProcessContainer,account,system);
        userProcessContainer.add("Manage Restaurents",personalInfo);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
        
    }//GEN-LAST:event_updateInfoActionPerformed

    private void viewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersActionPerformed
        OrderHistory orderHistory=new OrderHistory(userProcessContainer,account,system);
        userProcessContainer.add("Manage Restaurents",orderHistory);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrdersActionPerformed

    private void placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderActionPerformed
        CustomerAreaJPanel1 customerPanel=new CustomerAreaJPanel1(userProcessContainer,account,system);
        userProcessContainer.add("Manage Restaurents",customerPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_placeOrderActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton placeOrder;
    private javax.swing.JButton updateInfo;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewOrders;
    // End of variables declaration//GEN-END:variables
    
}
