/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import hospital.Encounter;
import hospital.EncounterHistory;
import hospital.Patient;
import hospital.PatientDirectory;
import hospital.Person;
import hospital.PersonDirectory;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manthanwadiwala
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */

    EncounterHistory encounterHistory;
    
    public ReportJPanel(EncounterHistory encounterHistory) {
        initComponents();
        
        this.encounterHistory = encounterHistory;
        //c1Panel.setVisible(false);
        //c2Panel.setVisible(false);
        populateTable();
        getCommunities();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableLegend = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ag1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ag2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ag3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ag4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ag11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ag12 = new javax.swing.JLabel();
        ag13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ag14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel1.setText("Patient Visit History");

        JTableLegend.setBackground(new java.awt.Color(8, 34, 137));
        JTableLegend.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        JTableLegend.setForeground(new java.awt.Color(255, 255, 255));
        JTableLegend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0 - 20", "60", "70"},
                {"21 - 40", "70", "80"},
                {"41 - 80", "65", "75"},
                {"80 +", "67", "77"}
            },
            new String [] {
                "Age Range(Years)", "Upper Limit", "Lower Limit"
            }
        ));
        JTableLegend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableLegendMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableLegend);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel2.setText("Patients with Abnormalities");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel3.setText("Select a community: ");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel4.setText("Select a community: ");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        tblPerson.setBackground(new java.awt.Color(8, 34, 137));
        tblPerson.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        tblPerson.setForeground(new java.awt.Color(255, 255, 255));
        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Age", "Gender", "House", "Community", "City", "Blood Pressure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPerson);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel5.setText("Normal Patient Blood Pressure Reference");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setText("Age Range (Years)");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel8.setText("No. Of Patients");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel7.setText("0 - 20");

        ag1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ag1.setText("ag1");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel9.setText("21 - 40");

        ag2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ag2.setText("ag2");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel10.setText("41 - 80");

        ag3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ag3.setText("ag3");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel11.setText("81 +");

        ag4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ag4.setText("ag4");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel12.setText("Age Range (Years)");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel14.setText("No. Of Patients");

        ag11.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ag11.setText("ag11");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel13.setText("0 - 20");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel15.setText("21 - 40");

        ag12.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ag12.setText("ag12");

        ag13.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ag13.setText("ag13");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel16.setText("41 - 80");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel17.setText("81 +");

        ag14.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        ag14.setText("ag14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11)
                                                .addGap(65, 65, 65)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(ag4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))
                                        .addGap(127, 127, 127)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ag1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ag2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ag3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ag14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ag13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ag12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ag11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ag1)
                    .addComponent(jLabel13)
                    .addComponent(ag11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ag2)
                    .addComponent(jLabel15)
                    .addComponent(ag12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ag3)
                    .addComponent(jLabel16)
                    .addComponent(ag13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ag4)
                    .addComponent(jLabel17)
                    .addComponent(ag14))
                .addGap(141, 141, 141))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(597, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String community = jComboBox1.getSelectedItem().toString();
        System.out.println(community);
        populateAbnormalitiesC1(community);
                
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String community = jComboBox2.getSelectedItem().toString();
        System.out.println(community);
        populateAbnormalitiesC2(community);
                
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void tblPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPersonMouseClicked

    private void JTableLegendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableLegendMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_JTableLegendMouseClicked

        private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        model.setRowCount(0);
        //int i=0;
        
        for(Encounter p : encounterHistory.getEncounterHistory()){
            
            Object[] row = new Object[8];
            //row[0] = f.getId();
            row[0] = p.getPatientId();
            row[1] = p.getName();
            row[2] = p.getAge();
            row[3] = p.getGender();
            row[4] = p.getHouse();
            row[5] = p.getCommunity();
            row[6] = p.getCity();
            row[7] = p.getBloodPressure();
            model.addRow(row);
        }
    }
        
        private void getCommunities()
        {
            
            jComboBox1.removeAllItems();
            jComboBox2.removeAllItems();
            int size=encounterHistory.getEncounterHistory().size();
            ArrayList<String> comm = new ArrayList<String>();
            for (int i = 0; i < size; i++) {
              comm.add(encounterHistory.getEncounterHistory().get(i).getCommunity());
            }
            HashSet<String> communities = new HashSet<String>(comm);
            jComboBox1.addItem("Select");
            jComboBox2.addItem("Select");
            for(String s : communities)
            {
                jComboBox1.addItem(s);
                jComboBox2.addItem(s);
            }
            
            
        }
        private void populateAbnormalitiesC1(String community)
        {
           ArrayList<String> a1 = new ArrayList<String>(); 
           ArrayList<String> a2 = new ArrayList<String>();
           ArrayList<String> a3 = new ArrayList<String>();
           ArrayList<String> a4 = new ArrayList<String>();
           
           for(Encounter e : encounterHistory.getEncounterHistory())
            {
                if(e.community.equals(community))
                {
                    //c1Panel.setVisible(true);
                        if((e.getAge() <= 20 && e.getBloodPressure() <= 60) || (e.getAge() <= 20 && e.getBloodPressure() >= 60))
                        {                           
                            a1.add(Integer.toString(e.getPatientId()));
                        }
                        if((e.getAge() >= 21 && e.getAge() <= 40 && e.getBloodPressure() <= 70) || (e.getAge() >= 21 && e.getAge() <= 40 && e.getBloodPressure() >=80))
                        {
                            a2.add(Integer.toString(e.getPatientId()));
                        }
                        if((e.getAge() >= 41 && e.getAge() <= 80 && e.getBloodPressure() <= 65) || (e.getAge() >= 41 && e.getAge() <= 80 && e.getBloodPressure() >=75))
                        {
                            a3.add(Integer.toString(e.getPatientId()));
                        }
                        if((e.getAge() >= 81 && e.getBloodPressure() <= 67) || (e.getAge() >= 81 && e.getBloodPressure() >=77))
                        {
                            a4.add(Integer.toString(e.getPatientId()));
                        }
                }
                
                
            }
           
           HashSet<String> h1 = new HashSet<String>(a1);
           ag1.setText(Integer.toString(h1.size()));
           HashSet<String> h2 = new HashSet<String>(a2);
           ag2.setText(Integer.toString(h2.size()));
           HashSet<String> h3 = new HashSet<String>(a3);
           ag3.setText(Integer.toString(h3.size()));
           HashSet<String> h4 = new HashSet<String>(a4);
           ag4.setText(Integer.toString(h4.size()));
  
  
                       
        }
        
              private void populateAbnormalitiesC2(String community)
        {
           ArrayList<String> a11 = new ArrayList<String>(); 
           ArrayList<String> a12 = new ArrayList<String>();
           ArrayList<String> a13 = new ArrayList<String>();
           ArrayList<String> a14 = new ArrayList<String>();
           
           for(Encounter e : encounterHistory.getEncounterHistory())
            {
                if(e.community.equals(community))
                {
                    //c2Panel.setVisible(true);
                        if((e.getAge() <= 20 && e.getBloodPressure() <= 60) || (e.getAge() <= 20 && e.getBloodPressure() >= 60))
                        {                           
                            a11.add(Integer.toString(e.getPatientId()));
                        }
                        if((e.getAge() >= 21 && e.getAge() <= 40 && e.getBloodPressure() <= 70) || (e.getAge() >= 21 && e.getAge() <= 40 && e.getBloodPressure() >=80))
                        {
                            a12.add(Integer.toString(e.getPatientId()));
                        }
                        if((e.getAge() >= 41 && e.getAge() <= 80 && e.getBloodPressure() <= 65) || (e.getAge() >= 41 && e.getAge() <= 80 && e.getBloodPressure() >=75))
                        {
                            a13.add(Integer.toString(e.getPatientId()));
                        }
                        if((e.getAge() >= 81 && e.getBloodPressure() <= 67) || (e.getAge() >= 81 && e.getBloodPressure() >=77))
                        {
                            a14.add(Integer.toString(e.getPatientId()));
                        }
                }
                              
            }
           
           HashSet<String> h11 = new HashSet<String>(a11);
           ag11.setText(Integer.toString(h11.size()));
           HashSet<String> h12 = new HashSet<String>(a12);
           ag12.setText(Integer.toString(h12.size()));
           HashSet<String> h13 = new HashSet<String>(a13);
           ag13.setText(Integer.toString(h13.size()));
           HashSet<String> h14 = new HashSet<String>(a14);
           ag14.setText(Integer.toString(h14.size()));
  
                       
        }
        
 
                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableLegend;
    private javax.swing.JLabel ag1;
    private javax.swing.JLabel ag11;
    private javax.swing.JLabel ag12;
    private javax.swing.JLabel ag13;
    private javax.swing.JLabel ag14;
    private javax.swing.JLabel ag2;
    private javax.swing.JLabel ag3;
    private javax.swing.JLabel ag4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPerson;
    // End of variables declaration//GEN-END:variables
}
